language: java
jdk:
  - openjdk8
install: true
script: mvn cobertura:cobertura
after_success:
# Move the code coverage results to codecov
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2

#deploy:
#  provider: script
#  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
#  skip_cleanup: true
#  on:
#    tags: true
